### ISSUE TITLE
Testimonials - Hanging Puncuation

### ISSUE THREAD

**Issue by kentmacdonald** [Canary-PrintDesign/highridge#1]
Hi @Sinetheta . I've into a little bit of a rabbit hole. The mock-up is designed with hanging punctuation. Which I've found difficult to code. What would the easiest way to code hanging punctuation be or how to achieve the same result?

<img width="363" alt="testimonial" src="https://user-images.githubusercontent.com/29032538/27503832-2ae24c62-5835-11e7-90fd-78c9d693a692.png">

Right now I have a branch for testimonials up, but I haven't pushed the SCSS or the HTML.erb files yet.

**Comment by Sinetheta** [comment]
Hey @kentmacdonald I might try adding `::before` and `::after` elements with background images if you want quotation marks that look "just like that". Here's a website with a few examples. http://www.hongkiat.com/blog/stylish-blockquotes-pullquotes/

**Comment by adamish717** [comment]
https://github.com/Canary-PrintDesign/highridge/commit/74f65615e5a09f770bfb7fc17afc27b7a7653e3f
